# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG RUNTIME_UID=1000
ARG RUNTIME_GID=1000
RUN mkdir -p /opt/aurora/bin /state /work /config /tls \
 && chown -R "${RUNTIME_UID}:${RUNTIME_GID}" /opt/aurora /state /work /config /tls
COPY agent/aurora-agent /opt/aurora/bin/aurora-agent
RUN chmod 0555 /opt/aurora/bin/aurora-agent
USER ${RUNTIME_UID}:${RUNTIME_GID}
ENTRYPOINT ["/opt/aurora/bin/aurora-agent"]
